### ISSUE TITLE
Unikernel runtime Integration TODOs

### ISSUE THREAD

**Issue by Crazykev** [kubernetes/frakti#181]
Basic framework:
- [ ] Metadata Store.
    - [x] [P0] In-memory metadata store. #180 @Crazykev
    - [ ] [P1] On-disk metadata store.
- [x] [P0] Sandbox Manager #180 @Crazykev
- [x] [P0] Container Manager #180 @Crazykev
- [ ] [P0] Image Manager #227 @Crazykev

Life Cycle:
- [x] Sandbox Management. #223 @Crazykev
    - [x] [P0] RunPodSandbox 
    - [x] [P0] StopPodSandbox
    - [x] [P0] RemovePodSandbox
    - [x] [P0] ListPodSandbox
    - [x] [P0] PodSandboxStatus
- [x] Container Management. #223 @Crazykev
    - [x] [P0] CreateContainer
    - [x] [P0] StartContainer
    - [x] [P0] StopContainer
    - [x] [P0] RemoveContainer
    - [x] [P0] ListContainers
    - [x] [P0] ContainerStatus
- [ ] Image Management. #227 @Crazykev
    - [ ] [P0] ListImages
    - [ ] [P0] PullImages
    - [ ] [P0] RemoveImages
    - [ ] [P0] ImageStatus
    - [ ] [P2] ImageFsInfo

Others:
- [ ] Network:
    - [ ] [P1] Integrate CNI plugin.
- [ ] Volume:
    - [ ] [P2] Flex volume
- [ ] Streaming:
    - [ ] [P2] ExecSync
    - [ ] [P2] Exec
    - [ ] [P2] Attach
    - [ ] [P2] PortForward
- [ ] [P2] Logging #226 

/cc Frakti Maintainers @feiskyer @resouer

**Comment by resouer** [comment]
Close, as most have been solved

**Comment by photoszzt** [comment]
I want to use this unikernel runtime. Without CNI plugin, is that mean I can't make network connection inside Kubernetes cluster?

**Comment by resouer** [comment]
@photoszzt Currently it's not fully implemented.
